dist: trusty
sudo: required
language: go
go:
- "1.12"

services:
  - redis-server
  - postgresql
  - docker

env:
  global:
    - DOCKER_USERNAME=proctorbuilder
    - secure: "ZCOM7TMiOsBO55V0VfAI1WQKODLZ4SUq50ngjZBJ2RfrOhHZ9zAqJgjw32bJtzUxuFX7Ez/44UEwd/Z28zbQjnzvIm8jwAwM+zxGH8zPlT9K9nuEN5edCO8oCYb5IdN4uPQkDw2w9FSNkRf8WfgS5Ru53SGiH+SVf2x/DT767HyP8EKhHWXJkKloxvR8wx7dSTr0vyQiNrslhh3EAVGQciZXLh2c6/pkZr0z/I5TpQnvWbvU0w9n9CqhhOaDiYI5zgKrpD/BdnYBmZtxfWO/RDyivacLDgozGcrV3iTJ6FkDbMgmhzrF0sAQL9LSrDOzUq6Yfe476c5BRHPgvh/gBHrpY6y7jmFGQ4vxER+vI9/rVILRLQfUSAYJBwuTAu7Wf/lZulw0GoQfIdaKa8RBCItaEN47HAPglxnPJBcl1ClYLBNc5XaHARdpKRurRz64AtBjCbTmoeUrdw9qktnKHSzxIPGQT1nKGvoizjpLUOURSwCp1T0GXxgcNX/65S/MruSFk5wf6jRz5x7ErVlv8MJLXWORV3EUR8sieXUTL5K0d2jq4NaGYTkbg9v4DwcgxMEm579gn+9MHPWGrrbC/k5xM03HjGYX44MnZb7jLuC0TRaYgnh4V8pe+ffxRY/+FLqDAnGtT7CxJsEONFy9jZrG9wVm2e0wVUxU9KxPvWE="

before_script:
- sudo service redis-server start

stages:
  - test
  - name: docker publish
    if: (branch = master OR tag IS present) and type != pull_request

jobs:
  include:
    - stage: test
      script:
        - make db.setup test
    - stage: docker publish
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t proctorgojek/proctor-service:latest .
        - if [ -n "$TRAVIS_TAG" ]; then
          docker tag proctorgojek/proctor-service:latest proctorgojek/proctor-service:$TRAVIS_TAG;
          fi
        - docker images
        - docker push proctorgojek/proctor-service

#after_success:
#  - scripts/release.sh
